### ISSUE TITLE
Mobile dark mode text overflow unreadable

### ISSUE THREAD

**Issue by aaronallen8455** [haskell/hackage-server#1167]
I'm using chrome on my android phone and whenever text runs past the width of the screen, the dark mode background color does not extend past a single screen width resulting in white on white text.

![Screenshot_20230122-101724](https://user-images.githubusercontent.com/16817102/213927192-352d0eba-9603-46cd-8e13-026474245ddf.png)

**Comment by gbaz** [comment]
@peterbecich thoughts?

**Comment by phadej** [comment]
The problem&answer is right at the top of `hackage.css`

```css
html {
  background-color: white;
  width: 100%;
  height: 100%;
}

@media (prefers-color-scheme: dark) {
  body {
    background: #333;
    color: #fefefe;
  }
}
@media (prefers-color-scheme: light) {
  body {
    background: #fefefe;
    color: #333;
  }
}
```
