### ISSUE TITLE
New CSS skin doesn't show deprecated versions

### ISSUE THREAD

**Issue by ocramz** [haskell/hackage-server#702]

**Comment by gbaz** [comment]
Thanks, I'll take a look.

**Comment by Porges** [comment]
Suggestion 🙂 

```css
.deprecated { text-decoration: line-through }
```
